FROM python:3.9-slim

WORKDIR /app

COPY producer/requirements.txt producer/requirements.txt
RUN pip install --no-cache-dir -r producer/requirements.txt 

COPY . .

CMD ["python", "-u", "producer/producer.py"]