# notebook-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-eda-notebook
  labels:
    app: spark-eda-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-eda-notebook
  template:
    metadata:
      labels:
        app: spark-eda-notebook
    spec:
      containers:
        - name: spark-eda-notebook
          image: image-registry.openshift-image-registry.svc:5000/ds551-2025fall-cb9303/spark-eda-notebook:latest
          imagePullPolicy: Always

          # ---- OpenShift Commands ----
          command: ["jupyter", "lab"]
          args:
            - "--ip=0.0.0.0"
            - "--port=8888"
            - "--no-browser"
            - "--allow-root"
            - "--NotebookApp.token="
            - "--NotebookApp.password="
          
          # ---------------------------------
          ports:
            - name: jupyter
              containerPort: 8888
            - name: spark-ui
              containerPort: 4040

          env:
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: customer

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

          # readinessProbe:
          #   httpGet:
          #     path: "/"
          #     port: 8888
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          #   timeoutSeconds: 2

          # livenessProbe:
          #   httpGet:
          #     path: "/"
          #     port: 8888
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 2

      restartPolicy: Always
      terminationGracePeriodSeconds: 30

