apiVersion: v1
kind: Service
metadata:
  name: spark-eda-notebook
  labels:
    app: spark-eda-notebook
spec:
  selector:
    app: spark-eda-notebook
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
    - name: spark-ui
      port: 4040
      targetPort: 4040
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jupyter
  labels:
    app: spark-eda-notebook
spec:
  to:
    kind: Service
    name: spark-eda-notebook
  port:
    targetPort: jupyter
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: spark-ui
  labels:
    app: spark-eda-notebook
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  to:
    kind: Service
    name: spark-eda-notebook
  port:
    targetPort: spark-ui
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
